### ISSUE TITLE
Does not work, Configuration Broken.

### ISSUE THREAD

**Issue by osgyan** [ARCHLabs/ArchLabs-Conky-New-Syntax#4]
conky-sessionfile points to   conky -c /home/erik/.config/conky/AL-Text.conkyrc & sleep 1s

Whereas it should be conky -c  ~/.config/conky/AL-Text.conkyrc & sleep 1s
Please update the configuration

**Comment by erikdubois** [comment]
has been changed 
I will keep it in mind
