### ISSUE TITLE
conkyrc-workspace

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Conky-New-Syntax#5]
looks a bit strange
who will take this up
![conky](https://cloud.githubusercontent.com/assets/10594806/24612767/76228e88-1886-11e7-9b7f-d4975cb40e24.jpg)

**Comment by Dobbie03** [comment]
Just delete this one, it's not included in BL and it was just a Conky I liked.

**Comment by erikdubois** [comment]
ok will be deleted now
